### ISSUE TITLE
 not to redirect

### ISSUE THREAD

**Issue by alex-lenk** [wpcodevo/JWT_Authentication_React#1]
Can you please tell me how not to redirect from the main page to the '/login' page?

backend/src/middleware/deserializeUser.ts

**Comment by wpcodevo** [comment]
> Can you please tell me how not to redirect from the main page to the '/login' page?
> 
> backend/src/middleware/deserializeUser.ts

Based on the current implementation of the frontend and backend applications, the main page displays a list of posts retrieved from the backend. The route to fetch the posts is protected on the backend, requiring authentication to access it.

In the frontend, we have implemented logic that redirects the user to the `/login` page if authentication fails or if refreshing the access token fails. To prevent the redirection from the main page to the `/login` page when authentication fails, you need to make some changes.

To do this, remove the `router.use(deserializeUser, requireUser);` middleware from the top of the GET and POST endpoints in the `/backend/src/routes/post.route.ts` file. Instead, apply the `deserializeUser` and `requireUser` middleware only to the POST route.

By making this adjustment, once the GET request to `/api/posts` is successful, you won't be redirected to the `/login` page since the route is not protected. I hope this helps you out. If you encounter any other issues, please let me know, and I'll be glad to assist you further.
